FROM envoyproxy/envoy-dev:latest

ENV DNS_NAME=""

RUN apt-get update && apt-get -q install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

ADD start_envoy.sh /start_envoy.sh
ADD envoy.yaml /etc/envoy.yaml

RUN chmod +x /start_envoy.sh

ENTRYPOINT ["/bin/sh"]

EXPOSE 443

CMD ["start_envoy.sh"]
